import org.code.neighborhood.*;

public class BackgroundPainterExtras extends PainterPlus {

  public void paintExtra1(String color){
    move();
    move();
    setPaint(5);
    while(hasPaint()){
     paint(color);
      move();
    }
    turnRight();
    move();
    turnRight();
    setPaint(7);
    while(hasPaint()){
     paint(color);
     move();
    }
    turnLeft();
    move();
    turnLeft();
    move();
    move();
    setPaint(5);
    while(hasPaint()){
     paint(color);
      move();
    }
    turnRight();
    move();
    turnRight();
    move();
    move();
    setPaint(2);
    while(hasPaint()){
     paint(color);
      move();
    }
    while(canMove()){
      move();
    }
    turnLeft();
    while(canMove()){
    move();
    }
  }

  public void paintExtra2(String color){
    while(canMove()){
      move();
    }
   setPaint(15);
    turnRight();
      paint(color);
      move();
      paint(color);
      move();
      paint(color);
    turnRight();
    move();
    turnRight();
      paint(color);
      move();
      paint(color);
      move();
      paint(color);
    turnLeft();
    move();
    turnLeft();
      paint(color);
      move();
      paint(color);
    turnRight();
    move();
      move();
      paint(color);
      move();
      paint(color);
    turnLeft();
    turnLeft();
    move();
    turnRight();
    move();
    move();
    move();
       paint(color);
       turnLeft();
       move();
       turnLeft();
       move();
       paint(color);
    turnRight();
    move();
    move();
    turnRight();
    move();
       paint(color);
       move();
       paint(color);
    move();
    move();
    move();
    move();
    move();
    move();
       paint(color);
    while(canMove()){
      move();
    }
    turnRight();
    while(canMove()){
      move();
    }
  }
    
  }